CREATE TABLE MOVIE(
ID NUMBER,
CONSTRAINT MOVIE_PK PRIMARY KEY (ID),
--CONSTRAINT CONST-NAME CONSTRAINT TYPE (COLUMN NAME)
TITLE NUMBER UNIQUE CHECK (TITLE <= 50),
DIRECTOR NVARCHAR2 (20),
YEAR NUMBER,
LENGTH_MINS NUMBER CHECK (LENGTH_MINS BETWEEN 10 AND 200)
);

INSERT INTO MOVIE
--VALUES(014,02,'JMOT', 1995 ,30);
VALUES(015,03,'YOLUP', 1996 ,35);

INSERT INTO MOVIE
--VALUES(014,02,'JMOT', 1995 ,30);
VALUES(015,03,'YOLUP', 1996 ,35);
--SELECT column1, column2 - FROM table_name
--WHERE conditions
--GROUP BY column_name

SELECT DIRECTOR, SUM(TITLE) FROM MOVIE
GROUP BY DIRECTOR;

SELECT DIRECTOR, SUM(DOMESTIC_SALES) FROM MOVIE_STAT
GROUP BY DIRECTOR;

SELECT DIRECTOR, SUM(INTERNATIONAL_SALES) FROM MOVIE_STAT
GROUP BY DIRECTOR;

--ВЫБОРКА ПО ПОЛЮ YEAR ПО УБЫВАНИЮ
SELECT * FROM MOVIE
ORDER BY YEAR DESC;

--ВЫБОРКА ПО ПОЛЮ INTERNATIONAL_SALES ПО УБЫВАНИЮ
SELECT * FROM MOVIE_STAT
ORDER BY INTERNATIONAL_SALES DESC;


