CREATE TABLE ORDERNEW(
ID NUMBER,
CONSTRAINT ORDERNEW_PK PRIMARY KEY (ID),
--CONSTRAINT CONST-NAME CONSTRAINT TYPE (COLUMN NAME)
CONSTRAINT  ORDERNEW_CHECK CHECK (ID != 10000),
USER_ID NUMBER UNIQUE,
ROOM_ID NUMBER UNIQUE,
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID DECIMAL(10,2)
);